[[redirects]]
from = "/resume.php"
to = "https://www.linkedin.com/in/bradyjfrey/"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/error.html"
status = 404

[[redirects]]
from = "/old"
to = "https://www.bradyjfrey.com"
status = 301

[[redirects]]
from = "/old/randyvo"
to = "https://www.bradyjfrey.com"
status = 301

[[redirects]]
from = "/about"
to = "https://www.bradyjfrey.com"
status = 301
